-- begin PETCLINIC_ADDRESS
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_COUNTRY foreign key (COUNTRY_ID) references PETCLINIC_COUNTRY(ID)^
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_STATE foreign key (STATE_ID) references PETCLINIC_STATE(ID)^
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_CITY foreign key (CITY_ID) references PETCLINIC_CITY(ID)^
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_STREET foreign key (STREET_ID) references PETCLINIC_STREET(ID)^
create index IDX_PETCLINIC_ADDRESS_COUNTRY on PETCLINIC_ADDRESS (COUNTRY_ID)^
create index IDX_PETCLINIC_ADDRESS_STATE on PETCLINIC_ADDRESS (STATE_ID)^
create index IDX_PETCLINIC_ADDRESS_CITY on PETCLINIC_ADDRESS (CITY_ID)^
create index IDX_PETCLINIC_ADDRESS_STREET on PETCLINIC_ADDRESS (STREET_ID)^
-- end PETCLINIC_ADDRESS
-- begin PETCLINIC_VISIT
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ASSIGNED_NURSE foreign key (ASSIGNED_NURSE_ID) references SEC_USER(ID)^
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_PET foreign key (PET_ID) references PETCLINIC_PET(ID)^
create index IDX_PETCLINIC_VISIT_ASSIGNED_NURSE on PETCLINIC_VISIT (ASSIGNED_NURSE_ID)^
create index IDX_PETCLINIC_VISIT_PET on PETCLINIC_VISIT (PET_ID)^
-- end PETCLINIC_VISIT
-- begin PETCLINIC_OWNER
alter table PETCLINIC_OWNER add constraint FK_PETCLINIC_OWNER_ADDRESS foreign key (ADDRESS_ID) references PETCLINIC_ADDRESS(ID)^
-- end PETCLINIC_OWNER
-- begin PETCLINIC_STREET
alter table PETCLINIC_STREET add constraint FK_PETCLINIC_STREET_CITY foreign key (CITY_ID) references PETCLINIC_CITY(ID)^
create index IDX_PETCLINIC_STREET_CITY on PETCLINIC_STREET (CITY_ID)^
-- end PETCLINIC_STREET
-- begin PETCLINIC_PET
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_TYPE foreign key (TYPE_ID) references PETCLINIC_PET_TYPE(ID)^
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_OWNER foreign key (OWNER_ID) references PETCLINIC_OWNER(ID)^
create unique index IDX_PETCLINIC_PET_ID_UNQ on PETCLINIC_PET (IDENTIFICATION_NUMBER, DELETE_TS)^
create index IDX_PETCLINIC_PET_TYPE on PETCLINIC_PET (TYPE_ID)^
create index IDX_PETCLINIC_PET_OWNER on PETCLINIC_PET (OWNER_ID)^
-- end PETCLINIC_PET
-- begin PETCLINIC_CITY
alter table PETCLINIC_CITY add constraint FK_PETCLINIC_CITY_STATE foreign key (STATE_ID) references PETCLINIC_STATE(ID)^
create index IDX_PETCLINIC_CITY_STATE on PETCLINIC_CITY (STATE_ID)^
-- end PETCLINIC_CITY
-- begin PETCLINIC_STATE
alter table PETCLINIC_STATE add constraint FK_PETCLINIC_STATE_COUNTRY foreign key (COUNTRY_ID) references PETCLINIC_COUNTRY(ID)^
create index IDX_PETCLINIC_STATE_COUNTRY on PETCLINIC_STATE (COUNTRY_ID)^
-- end PETCLINIC_STATE
-- begin PETCLINIC_VETERINARIAN_SPECIALTY_LINK
alter table PETCLINIC_VETERINARIAN_SPECIALTY_LINK add constraint FK_VETSPE_VETERINARIAN foreign key (VET_ID) references PETCLINIC_VETERINARIAN(ID)^
alter table PETCLINIC_VETERINARIAN_SPECIALTY_LINK add constraint FK_VETSPE_SPECIALTY foreign key (SPECIALTY_ID) references PETCLINIC_SPECIALTY(ID)^
-- end PETCLINIC_VETERINARIAN_SPECIALTY_LINK
