alter table PETCLINIC_STATE add constraint FK_PETCLINIC_STATE_COUNTRY foreign key (COUNTRY_ID) references PETCLINIC_COUNTRY(ID);
create index IDX_PETCLINIC_STATE_COUNTRY on PETCLINIC_STATE (COUNTRY_ID);
