alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_COUNTRY foreign key (COUNTRY_ID) references PETCLINIC_COUNTRY(ID);
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_STATE foreign key (STATE_ID) references PETCLINIC_STATE(ID);
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_CITY foreign key (CITY_ID) references PETCLINIC_CITY(ID);
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_STREET foreign key (STREET_ID) references PETCLINIC_STREET(ID);
create index IDX_PETCLINIC_ADDRESS_COUNTRY on PETCLINIC_ADDRESS (COUNTRY_ID);
create index IDX_PETCLINIC_ADDRESS_STATE on PETCLINIC_ADDRESS (STATE_ID);
create index IDX_PETCLINIC_ADDRESS_CITY on PETCLINIC_ADDRESS (CITY_ID);
create index IDX_PETCLINIC_ADDRESS_STREET on PETCLINIC_ADDRESS (STREET_ID);
